Process_Management/force-app/main/default/objects/Client__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Process_Management/force-app/main/default/objects/Job__c.object
<CustomObject>
    <fields>
        <fullName>Stream__c</fullName>
        <label>Stream</label>
        <referenceTo>Stream__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Process_Management/force-app/main/default/objects/Stream__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>Streams</relationshipLabel>
        <relationshipName>Streams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Stream</label>
    <nameField>
        <label>Stream Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Streams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Process_Management/force-app/main/default/objects/Time_Report__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <formula>Job__r.Stream__r.Client__r.Name</formula>
        <label>Client</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Time Reports</relationshipLabel>
        <relationshipName>Time_Reports</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Time Report</label>
    <nameField>
        <displayFormat>TR# {00000}</displayFormat>
        <label>Time Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Process_Management/force-app/main/default/classes/DataGeneratorTest.cls
@isTest
private class DataGeneratorTest {
    
    @isTest
    static void generateDataTest() {
        Test.startTest();
        FrontResponseWrapper result = DataGenerator.generateRandomData();
        Test.stopTest();
        System.assert(result.isSuccess);
        System.assert([SELECT Id FROM Task].size() > 0);
        System.assert([SELECT Id FROM Event].size() > 0);
        System.assert([SELECT Id FROM Account].size() > 0);
        System.assert([SELECT Id FROM Time_Report__c].size() > 0);
        System.assert([SELECT Id FROM Client__c].size() > 0);
        System.assert([SELECT Id FROM Job__c].size() > 0);
        System.assert([SELECT Id FROM Stream__c].size() > 0);
    }

    @isTest
    static void deleteAllDataTest() {
        FrontResponseWrapper generationResult = DataGenerator.generateRandomData();
        Test.startTest();
        FrontResponseWrapper deletionResult = DataGenerator.deleteAllData();
        Test.stopTest();
        System.assert(deletionResult.isSuccess);
        System.assert([SELECT Id FROM Task].isEmpty());
        System.assert([SELECT Id FROM Event].isEmpty());
        System.assert([SELECT Id FROM Account].isEmpty());
        System.assert([SELECT Id FROM Time_Report__c].isEmpty());
        System.assert([SELECT Id FROM Client__c].isEmpty());
        System.assert([SELECT Id FROM Job__c].isEmpty());
        System.assert([SELECT Id FROM Stream__c].isEmpty());
    }
}