Process_Management/force-app/main/default/objects/Job__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_Spent__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Time Spent (h)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Process_Management/force-app/main/default/classes/TH_JobTrigger.cls
public without sharing class TH_JobTrigger extends TriggerHandler.DelegateBase {

    Map<Job__c, Decimal> jobsWithTimeReported;

    public override void prepareAfter() {
        jobsWithTimeReported = new Map<Job__c, Decimal>();
    }

    public override void afterInsert(Map<Id, SObject> newObjectsMap) {
        Map<Id, Job__c> newJobsMap = (Map<Id, Job__c>)newObjectsMap;
        for (Id key : newJobsMap.keySet()) {
            Job__c newJob = newJobsMap.get(key);

            checkReportedTimeChanges(null, newJob);
        }
    }

    public override void afterUpdate(Map<Id, SObject> oldObjectsMap, Map<Id, SObject> newObjectsMap) {
        Map<Id, Job__c> newJobsMap = (Map<Id, Job__c>)newObjectsMap;
        Map<Id, Job__c> oldJobsMap = (Map<Id, Job__c>)oldObjectsMap;
        for (Id key : newJobsMap.keySet()) {
            Job__c newJob = newJobsMap.get(key);
            Job__c oldJob = oldJobsMap.get(key);

            checkReportedTimeChanges(oldJob, newJob);
        }
    }

    private void checkReportedTimeChanges(Job__c oldJob, Job__c newJob) {
        if(
            newJob.Assigned_To__c != null
            && ((oldJob != null && oldJob.Time_Spent__c != newJob.Time_Spent__c)                    //afterUpdate
                || (oldJob == null && newJob.Time_Spent__c != null && newJob.Time_Spent__c != 0)   //afterInsert
            )
        ) {
            jobsWithTimeReported.put(newJob, oldJob != null ? newJob.Time_Spent__c - oldJob.Time_Spent__c : newJob.Time_Spent__c);
        }
            
    }

    public override void finish() {
        if(jobsWithTimeReported != null && !jobsWithTimeReported.isEmpty())
            TimeReportManager.createTimeReports(jobsWithTimeReported);
    }

}