Process_Management/force-app/main/default/objects/Job__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Reminder_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reminder Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Time_Planned__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Time Planned (h)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Time_Spent__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Time Spent (h)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Process_Management/force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>Allow_Email_Notification__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow Email Notification</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Process_Management/force-app/main/default/globalValueSets/Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>TO DO</fullName>
        <default>true</default>
        <label>TO DO</label>
    </customValue>
    <customValue>
        <fullName>IN PROGRESS</fullName>
    </customValue>
    <customValue>
        <fullName>DONE</fullName>
    </customValue>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

Process_Management/force-app/main/default/classes/DueDateIsComingBatchTest.cls
@IsTest
private class DueDateIsComingBatchTest {
    @TestSetup
    static void dataSetup() {
        User testUser = TestHelper.createUser(new User(Allow_Email_Notification__c = true), true);
        TestHelper.createJobs(new Job__c(Assigned_To__c = testUser.Id, 
                                            Status__c = CommonUtility.JOB_STATUS_INPROGRESS,
                                            Due_Date__c = Datetime.now(),
                                            Reminder_Sent__c = false,
                                            Time_Planned__c = 10,
                                            Time_Spent__c = 4), 10, true, false);
    }

    @isTest
    static void testBatchExecution(){
        Test.startTest();
        DueDateIsComingBatch m = new DueDateIsComingBatch();
        System.schedule('DueDateIsComingBatch Processing 0', '0 0 * * * ?', m);
        Test.stopTest();
    }
}