Process_Management/force-app/main/default/objects/Job__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>DateTime</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Process_Management/force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>Allow_Email_Notification__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow Email Notification</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Process_Management/force-app/main/default/classes/DailyReminderBatchTest.cls
@IsTest
private class DailyReminderBatchTest {

    @TestSetup
    static void dataSetup() {
        User testUser = TestHelper.createUser(new User(Allow_Email_Notification__c = true), true);
        TestHelper.createJobs(new Job__c(Assigned_To__c = testUser.Id, Due_Date__c = Datetime.now()), 10, true);
    }

    @isTest
    static void testBatchExecution(){
        Test.startTest();
        DailyReminderBatch m = new DailyReminderBatch();
        System.schedule('DailyReminderBatch Processing 0', '0 0 * * * ?', m);
        Test.stopTest();
    }
}