Process_Management/force-app/main/default/objects/Job__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Process_Management/force-app/main/default/objects/Time_Report__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Time Reports</relationshipLabel>
        <relationshipName>Time_Reports</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reporter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reporter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Time_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_Reported__c</fullName>
        <label>Time Reported (h)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Time Report</label>
    <nameField>
        <displayFormat>TR# {00000}</displayFormat>
        <label>Time Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Process_Management/force-app/main/default/classes/TimeReportManager.cls
public without sharing class TimeReportManager {
    public static createTimeReports(Map<Job__c, Decimal> jobsWithTimeReported) {
        List<Time_Report__c> timeReportToInsert = new List<Time_Report__c>();
        for(Job__c job : jobsWithTimeReported.keySet()) {
            timeReportToInsert.add(
                new Time_Report__c(
                    Job__c = job.Id,
                    Reporter__c = job.Assigned_To__c,
                    Time_Reported__c = jobsWithTimeReported.get(job),
                    Date__c = Date.today()
            ));
        }
        insert timeReportToInsert;
    }
}