Process_Management/force-app/main/default/objects/Job__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Time_Spent__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Time Spent (h)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Process_Management/force-app/main/default/objects/Time_Report__c.object
<CustomObject>
    <fields>
        <fullName>Job__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Time Reports</relationshipLabel>
        <relationshipName>Time_Reports</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_Reported__c</fullName>
        <label>Time Reported (h)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Time Report</label>
    <nameField>
        <displayFormat>TR# {00000}</displayFormat>
        <label>Time Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Process_Management/force-app/main/default/globalValueSets/Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>TO DO</fullName>
        <default>true</default>
        <label>TO DO</label>
    </customValue>
    <customValue>
        <fullName>IN PROGRESS</fullName>
    </customValue>
    <customValue>
        <fullName>DONE</fullName>
    </customValue>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

Process_Management/force-app/main/default/classes/TimeReportManagerTest.cls
@isTest
private class TimeReportManagerTest {

    @TestSetup
    static void dataSetuo() {
        TestHelper.createJobs(null, 10, true);
    }

    @isTest
    static void timeReportsCreation() {
        Map<Id, Job__c> jobMap = new Map<Id,Job__c>([SELECT Id, Time_Spent__c FROM Job__c]);
        for(Job__c job : jobMap.values()) {
            job.Time_Spent__c = Decimal.valueOf(TestHelper.createRandomNumber());
            job.Status__c = CommonUtility.JOB_STATUS_INPROGRESS;
        }
        Test.startTest();
        update jobMap.values();
        Test.stopTest();
        List<Time_Report__c> result = [SELECT Id, Time_Reported__c, Job__c FROM Time_Report__c];
        System.assert(!result.isEmpty());
        for(Time_Report__c tR : result) {
            System.assertEquals(jobMap.get(tR.Job__c).Time_Spent__c, tr.Time_Reported__c);
        }
    }

    @isTest
    static void timeReportsModified() {
        Map<Id, Job__c> jobMap = new Map<Id,Job__c>([SELECT Id, Time_Spent__c FROM Job__c]);
        for(Job__c job : jobMap.values()) {
            job.Time_Spent__c = Decimal.valueOf(TestHelper.createRandomNumber());
            job.Status__c = CommonUtility.JOB_STATUS_INPROGRESS;
        }
        update jobMap.values();
        Map<Id, Time_Report__c> relatedTimeReports = new Map<Id, Time_Report__c>([SELECT Id, Time_Reported__c, Job__c FROM Time_Report__c]);

        Test.startTest();
        for(Job__c job : jobMap.values()) {
            job.Time_Spent__c = job.Time_Spent__c + Decimal.valueOf(TestHelper.createRandomNumber());
        }
        update jobMap.values();
        Test.stopTest();
        List<Time_Report__c> updatedTimeReports = [SELECT Id, Time_Reported__c, Job__c FROM Time_Report__c];
        for(Time_Report__c tR : updatedTimeReports) {
            System.assertEquals(jobMap.get(tR.Job__c).Time_Spent__c, tr.Time_Reported__c);
        }
    }

}