Process_Management/force-app/main/default/objects/Job__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Next_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Next Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Previous Jobs</relationshipLabel>
        <relationshipName>PreviousJobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Second_Next_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Second Next Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Jobs (Second Next Job)</relationshipLabel>
        <relationshipName>PrevJob</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stream__c</fullName>
        <label>Stream</label>
        <referenceTo>Stream__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Process_Management/force-app/main/default/objects/Stream__c.object
<CustomObject>
    <fields>
        <fullName>JSON_Description__c</fullName>
        <label>JSON Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(
				Number_Of_Jobs_To_Do__c = Number_Of_Jobs__c, 
				&apos;TO DO&apos;,
				IF(Number_Of_Jobs_To_Do__c = Number_Of_Jobs_Done__c,
						&apos;DONE&apos;,
						&apos;IN PROGRESS&apos;
				)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Stream</label>
    <nameField>
        <label>Stream Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Streams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Process_Management/force-app/main/default/globalValueSets/Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>TO DO</fullName>
        <default>true</default>
        <label>TO DO</label>
    </customValue>
    <customValue>
        <fullName>IN PROGRESS</fullName>
    </customValue>
    <customValue>
        <fullName>DONE</fullName>
    </customValue>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

Process_Management/force-app/main/default/classes/JobManagerTest.cls
@isTest
private class JobManagerTest {

    @isTest
    static void changeJobToTemplateIfStreamIsTemplate() {
        Stream__c stream = TestHelper.createStream(new Stream__c(RecordTypeId = CommonUtility.getRecordTypeId(CommonUtility.SOBJECT_APINAME_STREAM, CommonUtility.STREAM_TYPE_STANDARD_TEMPLATE)), true);
        List<Job__c> jobList = TestHelper.createJobs(new Job__c(Stream__c = stream.Id), 10, false);
        Test.startTest();
        insert jobList;
        Test.stopTest();
        for(Job__c job : [SELECT Id, RecordTypeId FROM Job__c]) {
            System.assertEquals(CommonUtility.getRecordTypeId(CommonUtility.SOBJECT_APINAME_JOB, CommonUtility.JOB_TYPE_STANDARD_TEMPLATE), job.RecordTypeId);
        }
    }

    @isTest 
    static void updateLookupAfterRelatedJobDeletion() {
        Stream__c stream = TestHelper.createStream(new Stream__c(RecordTypeId = CommonUtility.getRecordTypeId(CommonUtility.SOBJECT_APINAME_STREAM, CommonUtility.STREAM_TYPE_STANDARD_TEMPLATE)), true);
        Job__c firstRelJob = TestHelper.createJob(new Job__c(Stream__c = stream.Id), true);
        Job__c secondRelJob = TestHelper.createJob(new Job__c(Stream__c = stream.Id), true);
        Job__c testJob = TestHelper.createJob(new Job__c(Stream__c = stream.Id, Next_Job__c = firstRelJob.Id, Second_Next_Job__c = secondRelJob.Id), true);
        Test.startTest();
        delete firstRelJob;
        Test.stopTest();

        Job__c testJobQueried = [SELECT Id, Next_Job__c, Second_Next_Job__c FROM Job__c WHERE Id =: testJob.Id];
        System.assertEquals(null, testJobQueried.Second_Next_Job__c);
        System.assertEquals(secondRelJob.Id, testJobQueried.Next_Job__c);
    }

    @isTest 
    static void cloneStreamWithJobsSucess() {
        Stream__c stream = TestHelper.createStream(null , true);
        Job__c firstRelJob = TestHelper.createJob(new Job__c(Stream__c = stream.Id), true);
        Job__c secondRelJob = TestHelper.createJob(new Job__c(Stream__c = stream.Id), true);
        Job__c testJob = TestHelper.createJob(new Job__c(Stream__c = stream.Id, Next_Job__c = firstRelJob.Id, Second_Next_Job__c = secondRelJob.Id), true);
        TestHelper.generateGraphJSONDescription(stream.Id);
        update stream;
        Map<Id, Job__c> jobMap = new Map<Id, Job__c>();
        jobMap.put(firstRelJob.Id, firstRelJob);
        jobMap.put(secondRelJob.Id, secondRelJob);
        jobMap.put(testJob.Id, testJob);
        Test.startTest();
        FrontResponseWrapper repsonse = JobManager.cloneStreamWithJobs(stream.Id);
        Test.stopTest();
        System.assert(repsonse.isSuccess);
        System.assertEquals(1, [SELECT Id FROM Stream__c WHERE Id <> :stream.Id].size());
        System.assertEquals(jobMap.keySet().size(), [SELECT Id FROM Job__c WHERE Id NOT IN :jobMap.keySet()].size());
    }

    @isTest 
    static void cloneStreamWithJobsError() {
        Stream__c stream = TestHelper.createStream(null , true);
        Id idTopass = stream.Id;
        delete stream;
        Test.startTest();
        FrontResponseWrapper repsonse = JobManager.cloneStreamWithJobs(idTopass);
        Test.stopTest();
        System.assert(!repsonse.isSuccess);
       
    }

    @isTest
    static void userJobsCount() {
        User testUser = TestHelper.createUser(null, true);
        List<Job__c> jobList = TestHelper.createJobs(new Job__c(Assigned_To__c = testUser.Id, Status__c = CommonUtility.JOB_STATUS_TODO), 10, true);
        Test.startTest();
        System.runAs(testUser) {
            System.assertEquals(jobList.size(), JobManager.getUserJobsCount());
            System.assertEquals(5, JobManager.getUserJobs(1,5,5).size());
        }
        Test.stopTest();
    }

    @isTest
    static void updateRelatedJSONStream() {
        Stream__c stream = TestHelper.createStream(null , true);
        List<Job__c> jobList = TestHelper.createJobs(new Job__c(Stream__c = stream.Id), 10, true);
        TestHelper.generateGraphJSONDescription(stream.Id);
        for(Integer i = 0; i < jobList.size(); i++) {
            if(i > 0) {
                jobList.get(i).Next_Job__c = jobList.get(i-1).Id;
            } 
            if(i > 1) {
                jobList.get(i).Second_Next_Job__c = jobList.get(i-2).Id;
            }
            jobList.get(i).Name = 'test' + String.valueOf(i);
            jobList.get(i).Status__c = CommonUtility.JOB_STATUS_INPROGRESS;
        }
        update jobList;
        Test.startTest();
        update jobList;
        TestHelper.generateGraphJSONDescription(stream.Id);
        JobManager.updateRelatedStreamJSON(new Map<Id, Job__c>(jobList));
        Test.stopTest();
        stream = [SELECT JSON_Description__c FROM Stream__c];
        for(Job__c job: jobList) {
            System.assert(stream.JSON_Description__c.contains(job.Name));
        }
    }
}