Process_Management/force-app/main/default/objects/Job__c.object
<CustomObject>
    <fields>
        <fullName>Stream__c</fullName>
        <label>Stream</label>
        <referenceTo>Stream__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Process_Management/force-app/main/default/objects/Stream__c.object
<CustomObject>
    <label>Stream</label>
    <nameField>
        <label>Stream Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Streams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Process_Management/force-app/main/default/classes/CommonUtility.cls
global without sharing class CommonUtility {

    // SOBJECT API NAMES
    global static final String SOBJECT_APINAME_ACCOUNT = 'Account';
    global static final String SOBJECT_APINAME_CONTACT = 'Contact';
    global static final String SOBJECT_APINAME_EVENT = 'Event';
    global static final String SOBJECT_APINAME_TASK = 'Task';
    global static final String SOBJECT_APINAME_JOB = 'Job__c';
    global static final String SOBJECT_APINAME_STREAM = 'Stream__c';

    // SOBJECT NAMES
    global static final String SOBJECT_NAME_ENTITY = 'Entity';
    global static final String SOBJECT_NAME_EMPLOYEE = 'Employee';
    global static final String SOBJECT_NAME_JOB = 'Job';
    global static final String SOBJECT_NAME_STREAM = 'Stream';

    // EMPLOYEE ROLE PICKLIST FIELD VALES
    global static final String EMPLOYEE_ROLE_MANAGER = 'Manager';
    global static final String EMPLOYEE_ROLE_REGULAR = 'Regular employee';

    // JOB STATUS PICKLIST FIELD VALES
    global static final String JOB_STATUS_TODO = 'TO DO';
    global static final String JOB_STATUS_INPROGRESS = 'IN PROGRESS';
    global static final String JOB_STATUS_DONE = 'DONE';

}