Process_Management/force-app/main/default/objects/Job__c.object
<CustomObject>
    <fields>
        <fullName>Next_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Next Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Previous Jobs</relationshipLabel>
        <relationshipName>PreviousJobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Second_Next_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Second Next Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Jobs (Second Next Job)</relationshipLabel>
        <relationshipName>PrevJob</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stream__c</fullName>
        <label>Stream</label>
        <referenceTo>Stream__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Process_Management/force-app/main/default/objects/Stream__c.object
<CustomObject>
    <label>Stream</label>
    <nameField>
        <label>Stream Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Streams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Process_Management/force-app/main/default/classes/JobManager.cls
public without sharing class JobManager {

    public static void checkJobToTemplateIfTemplateStream(Map<Id, List<Job__c>> jobsToCheckTemplate) {
        for(Stream__c templatSteam : [SELECT Id, RecordTypeId 
                                    FROM Stream__c 
                                    WHERE Id IN: jobsToCheckTemplate.keySet()
                                    AND RecordTypeId =: CommonUtility.getRecordTypeId(CommonUtility.SOBJECT_APINAME_STREAM, CommonUtility.STREAM_TYPE_STANDARD_TEMPLATE)]) {
            for(Job__c jobToChange : jobsToCheckTemplate.get(templatSteam.Id)) {
                jobToChange.RecordTypeId = CommonUtility.getRecordTypeId(CommonUtility.SOBJECT_APINAME_JOB, CommonUtility.JOB_TYPE_STANDARD_TEMPLATE);
            }
        }
    }

    public static void updateRelatedJobs(Set<Id> jobsIdForDeletion) {
        List<Job__c> jobsToUpdate = [SELECT Id, Next_Job__c, Second_Next_Job__c FROM Job__c WHERE Next_Job__c IN: jobsIdForDeletion AND Second_Next_Job__c != null];

        for(Job__c job : jobsToUpdate) {
            job.Next_Job__c = job.Second_Next_Job__c;
            job.Second_Next_Job__c = null;
        }
        update jobsToUpdate;
    }
}