Process_Management/force-app/main/default/objects/Job__c.object
<CustomObject>
    <fields>
        <fullName>Reminder_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reminder Sent</label>
        <type>Checkbox</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Process_Management/force-app/main/default/classes/ResetReminderSentBatchTest.cls
@IsTest
private class ResetReminderSentBatchTest {
    @TestSetup
    static void dataSetup() {
        TestHelper.createJobs(new Job__c(Reminder_Sent__c = true), 10, true, false);
    }

    @isTest
    static void testBatchExecution(){
        Test.startTest();
        ResetReminderSentBatch m = new ResetReminderSentBatch();
        System.schedule('ResetReminderSentBatch Processing 0', '0 0 * * * ?', m);
        Test.stopTest();
    }
}