Process_Management/force-app/main/default/objects/Job__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Next_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Next Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Previous Jobs</relationshipLabel>
        <relationshipName>PreviousJobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Second_Next_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Second Next Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Jobs (Second Next Job)</relationshipLabel>
        <relationshipName>PrevJob</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stream__c</fullName>
        <label>Stream</label>
        <referenceTo>Stream__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Process_Management/force-app/main/default/objects/Stream__c.object
<CustomObject>
    <fields>
        <fullName>JSON_Description__c</fullName>
        <label>JSON Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Stream</label>
    <nameField>
        <label>Stream Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Streams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Process_Management/force-app/main/default/classes/DAGCheckerTest.cls
@isTest
private class DAGCheckerTest {

    @testSetup
    static void dataSetup() {
        User testUser = TestHelper.createUser(null, true);
        Stream__c stream = TestHelper.createStream(new Stream__c() , true);
        List<Job__c> jobList = TestHelper.createJobs(new Job__c(Stream__c = stream.Id, Assigned_To__c = testUser.Id), 10, true, false);
        for(Integer i = 0; i < jobList.size(); i++) {
            if(i > 0) {
                jobList.get(i).Next_Job__c = jobList.get(i-1).Id;
            } 
            if(i > 1) {
                jobList.get(i).Second_Next_Job__c = jobList.get(i-2).Id;
            }
        }
        update jobList;
        TestHelper.generateGraphJSONDescription(new Set<Id>{stream.Id});
    }

    @isTest
    static void notDAGgraph() {
        Stream__c testStream = [SELECT Id, JSON_Description__c FROM Stream__c LIMIT 1];
        Map<String, Object> mappedGraph = (Map<String, Object>)JSON.deserializeUntyped(testStream.JSON_Description__c);
        List<Object> edges = (List<Object>)mappedGraph.get('edges');
        List<Object> nodes = (List<Object>)mappedGraph.get('nodes');
        Map<String, Object> startNodeNewEdge;
        Map<String, Object> endNodeNewEdge;
        for(Integer i = 0; i < nodes.size(); i++) {
            if(i == 2) {
                startNodeNewEdge = (Map<String, Object>)nodes.get(i);
            } 
            if(i == 4) {
                endNodeNewEdge = (Map<String, Object>)nodes.get(i);
            }
        }
        Test.startTest();
        FrontResponseWrapper response = DAGChecker.checkIfGraphIsDAG(JSON.serialize(edges), JSON.serialize(startNodeNewEdge), JSON.serialize(endNodeNewEdge), 10);
        Test.stopTest();
        System.assert(!response.isSuccess);
    }

    @isTest
    static void DAGgraph() {
        Stream__c testStream = [SELECT Id, JSON_Description__c FROM Stream__c LIMIT 1];
        List<Job__c> jobList = [SELECT Id, Name, Next_Job__c, Second_Next_Job__c FROM Job__c WHERE Stream__c =: testStream.Id ORDER BY Name ASC];
        for(Integer i = 0; i < jobList.size(); i++) {
            jobList.get(i).Next_Job__c = null;
            jobList.get(i).Second_Next_Job__c = null;
        }
        update jobList;
        TestHelper.generateGraphJSONDescription(new Set<Id>{testStream.Id});
        testStream = [SELECT Id, JSON_Description__c FROM Stream__c LIMIT 1];
        Map<String, Object> mappedGraph = (Map<String, Object>)JSON.deserializeUntyped(testStream.JSON_Description__c);
        List<Object> edges = (List<Object>)mappedGraph.get('edges');
        List<Object> nodes = (List<Object>)mappedGraph.get('nodes');
        Map<String, Object> startNodeNewEdge;
        Map<String, Object> endNodeNewEdge;
        for(Integer i = 0; i < nodes.size(); i++) {
            if(i == 4) {
                startNodeNewEdge = (Map<String, Object>)nodes.get(i);
            } 
            if(i == 0) {
                endNodeNewEdge = (Map<String, Object>)nodes.get(i);
            }
        }
        Test.startTest();
        FrontResponseWrapper response = DAGChecker.checkIfGraphIsDAG(JSON.serialize(edges), JSON.serialize(startNodeNewEdge), JSON.serialize(endNodeNewEdge), 10);
        Test.stopTest();
        System.assert(response.isSuccess);
    }
}